### ISSUE TITLE
Could not find code package file for [WheelMorph]. Installation of [DrGeo] failed.

### ISSUE THREAD

**Issue by cstes** [hilaire/cuis-xp#1]
Platform : OpenIndiana with cog-spur VM 5.0.3066-2020.0.1.0

squeak -version
5.0-202109241411-cog  Sat Sep 25 20:58:14 UTC 2021 /usr/gcc/7/bin/gcc 7.5.0 [Production Spur VM]
CoInterpreter VMMaker.oscog-eem.3074 uuid: fc13f6e9-1cc3-4535-a31d-5e7f5dafe75f Sep 25 2021
StackToRegisterMappingCogit VMMaker.oscog-eem.3071 uuid: ae226d69-be9f-4f7a-a138-0c85163277dd Sep 25 2021

I have cloned the latest Cuis from https://github.com/Cuis-Smalltalk/Cuis-Smalltalk-Dev.git
and copied Cuis5.0-4928.image to drgeo.image

I then run the Cuis updates (from the Changes menu) and update the image to Cuis 5.0 update #4957

Then I try to fileIn DrGeo.pkg.st but this gives the following error:

2021-10-29T18:43:56.688 process:40 1964181 Could not find code package file for [WheelMorph].
Installation of [DrGeo] failed.

Also the package WaitSpinner seems to be absent in my setup.

Where to find WheelMorph and WaitSpinner please ?

**Comment by hilaire** [comment]
DrGeo code is not hosted at Github. 
Check out http://dev.drgeo.eu and browse the code repository INSTALL instructions.
